#!/usr/bin/env bash
#shellcheck disable=2312
# Exit on error
set -euo pipefail

# shellcheck source=/dev/null
. ci/functions.sh

# Error handling
trap 'err "ERROR at $0 line ${BASH_LINENO[0]}. Exiting."; exit 1' ERR

if [[ -f /.dockerenv ]]; then
    warn "$0 needs to be run on host"
    fatal 1 "You need to be outside a docker container to run this script"
fi

cfg_file=config.json
env_file=.env

cat <<EOF >"${env_file}"
# automatically generated by $0

VERBOSE="$(jq -r '.build.verbose' "${cfg_file}")"
USE_CACHE="$(jq -r '.build.use_cache' "${cfg_file}")"

USER_ID="$(id -u)"
GROUP_ID="$(id -g)"

# base image for this project -- required if we cannot pull from docker hub
BASE_IMAGE="$(jq -r '.dependencies.image' "${cfg_file}")"
git_url_cli="$(jq -r '.dependencies.url' "${cfg_file}")"
git_repo_name="$(jq -r '.dependencies.repo_name' "${cfg_file}")"
git_branch="$(jq -r '.dependencies.branch' "${cfg_file}")"
clone_dir="$(jq -r '.dependencies.clone_in' "${cfg_file}")"
build_script="$(jq -r '.dependencies.local_script' "${cfg_file}")"


# image we are building for this project
DBG_RESULT_IMAGE="$(jq -r '.result_image.name' "${cfg_file}")"
DBG_HUB_TAG="$(jq -r '.result_image.hub_tag' "${cfg_file}")"
DBG_VERSION_TAG="$(jq -r '.result_image.version_tag' "${cfg_file}")"
DBG_FILE="$(jq -r '.result_image.file' "${cfg_file}")"
DBG_CONTEXT="$(jq -r '.result_image.context' "${cfg_file}")"
DBG_USERNAME="$(jq -r '.result_image.username' "${cfg_file}")"

EOF

info "Verify that no variables are assigned as null"
if grep -q '="null"' "${env_file}"; then
    fatal 1 "${env_file} file contains variables assigned to 'null'"
fi
